{{- include "common.setup" . }}
{{- define "syslog-ng.logrotatesidecar" -}}
{{- if .Values.logrotate.enabled }}
additionalContainers:
  logrotate:
    name: logrotate
    image: "{{ .Values.logrotateImage.repository }}:{{ .Values.logrotateImage.tag }}"
    env:
      - name: LOGS_DIRECTORIES
        value: "{{ .Values.persistence.logs.mountPath }}"
      - name: LOGROTATE_INTERVAL
        value: "{{ .Values.logrotate.interval }}"
      - name: LOGROTATE_COPIES
        value: "{{ .Values.logrotate.copies }}"
      - name: LOGROTATE_POSTROTATE_COMMAND
        value: "{{ .Values.logrotate.postrotate-command }}"
      - name: LOGROTATE_SIZE
        value: "{{ .Values.logrotate.size }}"
      - name: LOGROTATE_COMPRESSION
        value: "{{ ternary 'compress' 'nocompress' .values.logrotate.compress }}"
      - name: LOGROTATE_DELAYCOMPRESS
        value: "{{ .values.logrotate.delay-compress }}"
    volumeMounts:
      - name: logs
        mountPath: "/var/log"
{{- end }}
{{- end -}}
{{- include "syslog-ng.logrotatesidecar" . }}
{{ include "common.postSetup" . }}
