shareProcessNamespace: true

image:
  repository: tccr.io/truecharts/syslog-ng
  pullPolicy: IfNotPresent
  tag: v3.30.1

logrotateImage:
  repository: docker.io/blacklabelops/logrotate
  pullPolicy: IfNotPresent
  tag: 1.3

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 6601
        port: 6601
  syslog-udp:
    enabled: true
    ports:
      syslog-udp:
        enabled: true
        protocol: UDP
        targetPort: 5514
        port: 5514
  syslog-tls:
    enabled: true
    ports:
      syslog-tls:
        enabled: true
        targetPort: 6514
        port: 6514

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  logs:
    enabled: true
    mountPath: "/var/log"

{{ if .Values.logrotate.enabled }}
additionalContainers:
  logrotate:
    name: logrotate
    image: "{{ .Values.logrotateImage.repository }}:{{ .Values.logrotateImage.tag }}"
    env:
      - name: LOGS_DIRECTORIES
        value: "{{ .Values.persistence.logs.mountPath }}"
      - name: LOGROTATE_INTERVAL
        value: "{{ .Values.logrotate.interval }}"
      - name: LOGROTATE_COPIES
        value: "{{ .Values.logrotate.copies }}"
      - name: LOGROTATE_POSTROTATE_COMMAND
        value: "{{ .Values.logrotate.postrotate-command }}"
      - name: LOGROTATE_SIZE
        value: "{{ .Values.logrotate.size }}"
      - name: LOGROTATE_COMPRESSION
        value: "{{ ternary 'compress' 'nocompress' .values.logrotate.compress }}"
      - name: LOGROTATE_DELAYCOMPRESS
        value: "{{ .values.logrotate.delay-compress }}"
    volumeMounts:
      - name: logs
        mountPath: "/var/log"
{{ end }}
