image:
  repository: tccr.io/truecharts/syslog-ng
  pullPolicy: IfNotPresent
  tag: v3.30.1

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 6601
        port: 6601
  syslog-udp:
    enabled: true
    ports:
      syslog-udp:
        enabled: true
        protocol: UDP
        targetPort: 5514
        port: 5514
  syslog-tls:
    enabled: true
    ports:
      syslog-tls:
        enabled: true
        targetPort: 6514
        port: 6514

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
